from typing import Protocol, Any


class DatabaseConnectionAbstract(Protocol):
    def config(self, *args: Any, **kwargs: Any) -> Any: ...
    def login(self, *args: Any, **kwargs: Any) -> bool: ...
    def get_users(self, *args: Any, **kwargs: Any) -> list[dict]: ...
    def logout(self) -> bool: ...
    def change_pass(self, *args: Any, **kwargs: Any) -> Any: ...
