name: CI

on:
  pull_request:
    paths-ignore: ['docs/**', '**/README.rst']
  push:
    branches: [main]
    paths-ignore: ['docs/**', '**/README.rst']
  workflow_dispatch:

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run Ruff check
        run: poetry run ruff check

      - name: Run Ruff format
        run: poetry run ruff format --diff

      - name: Run Mypy
        run: poetry run mypy

      - name: Run complexipy
        run: poetry run complexipy .

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version-file: pyproject.toml

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: poetry install --with dev

    - name: Run Pytest
      run: poetry run pytest -vv
